name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, copilot/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: tdc_db_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    
    env:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/tdc_db_test
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: us-east-1
      S3_BUCKET: tdc-photos
      S3_ENDPOINT: http://localhost:9000
      REDIS_URL: redis://localhost:6379
      NODE_ENV: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json
      
      - name: Setup MinIO
        run: |
          # Start MinIO in background
          docker run -d \
            --name minio \
            -p 9000:9000 \
            -p 9001:9001 \
            -e MINIO_ROOT_USER=minioadmin \
            -e MINIO_ROOT_PASSWORD=minioadmin \
            minio/minio:latest \
            server /data --console-address ":9001"
          
          # Wait for MinIO to be ready
          sleep 10
          
          # Install MinIO client
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          
          # Configure MinIO client and create bucket
          ./mc alias set minio http://localhost:9000 minioadmin minioadmin
          ./mc mb minio/tdc-photos || true
      
      - name: Install dependencies
        working-directory: ./app
        run: npm ci
      
      - name: Generate Prisma client
        working-directory: ./app
        run: npx prisma generate
      
      - name: Run database migrations
        working-directory: ./app
        run: npx prisma db push
      
      - name: Run lint
        working-directory: ./app
        run: npm run lint
      
      - name: Run build
        working-directory: ./app
        run: npm run build
      
      - name: Start server in background
        working-directory: ./app
        run: |
          npm run dev &
          sleep 10
        env:
          CI: true
      
      - name: Run tests
        working-directory: ./app
        run: npm test -- --run
        env:
          CI: true
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy notification
        run: echo "🚀 Ready for deployment to production!"